In [1]:
import numpy as np
import pandas as pd

V1=np.array([1,3,6,5,7])
V2=np.array([7,7,5,8,12])
V3=np.array([6,12,5,6,14])

df=pd.DataFrame(
    {
        "V1": V1,
        "V2": V2,
        "V3": V3}
)

df=df.astype("float")
df

V1    V2    V3
0  1.0   7.0   6.0
1  3.0   7.0  12.0
2  6.0   5.0   5.0
3  5.0   8.0   6.0
4  7.0  12.0  14.0

In [2]:
from sklearn import preprocessing

In [3]:
preprocessing.scale(df) 
#ortalaması 0 std sapması 1 olacak şekilde standartlaştırma işlemi

array([[-1.57841037, -0.34554737, -0.70920814],
       [-0.64993368, -0.34554737,  0.92742603],
       [ 0.74278135, -1.2094158 , -0.98198051],
       [ 0.27854301,  0.08638684, -0.70920814],
       [ 1.2070197 ,  1.81412369,  1.47297076]])

NORMALİZASYON

In [4]:
preprocessing.normalize(df)
#0-1 aralğında dönüştürme

array([[0.10783277, 0.75482941, 0.64699664],
       [0.21107926, 0.49251828, 0.84431705],
       [0.64699664, 0.53916387, 0.53916387],
       [0.4472136 , 0.71554175, 0.53665631],
       [0.35491409, 0.60842415, 0.70982818]])

MIN - MAX DÖNÜŞÜMÜ

In [5]:
scaler = preprocessing.MinMaxScaler(feature_range = (10,20))

In [6]:
scaler.fit_transform(df)

array([[10.        , 12.85714286, 11.11111111],
       [13.33333333, 12.85714286, 17.77777778],
       [18.33333333, 10.        , 10.        ],
       [16.66666667, 14.28571429, 11.11111111],
       [20.        , 20.        , 20.        ]])

BİNARİZE DÖNÜŞÜM

In [7]:
binarizer = preprocessing.Binarizer(threshold=5).fit(df)
#threshold 5 dedik. 5in üzerine 1 girdi, altına 0 girdi

In [8]:
binarizer.transform(df)

array([[0., 1., 1.],
       [0., 1., 1.],
       [1., 0., 0.],
       [0., 1., 1.],
       [1., 1., 1.]])

0-1 DÖNÜŞÜMÜ

In [11]:
import seaborn as sns

tips = sns.load_dataset('tips')
df = tips.copy()
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [12]:
import seaborn as sns

tips = sns.load_dataset('tips')
df = tips.copy()
df_l=df.copy()
df_l.head()


#df = tips.copy()
#df.head()
#böyle yazınca da aynısı çıkıyor ama neden üstteki gibi 
#yaptığımızı anlamadım.

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [13]:
# sex değişkenini 01li değişkene çevir
df_l["yeni_sex"] = df_l["sex"].cat.codes
df_l.head()

#cat code yakaladığı değişkeni 1den dönüştürmeye başlar

total_bill   tip     sex smoker  day    time  size  yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         1
1       10.34  1.66    Male     No  Sun  Dinner     3         0
2       21.01  3.50    Male     No  Sun  Dinner     3         0
3       23.68  3.31    Male     No  Sun  Dinner     2         0
4       24.59  3.61  Female     No  Sun  Dinner     4         1

In [14]:
lbe= preprocessing.LabelEncoder()

In [15]:
df_l["daha_yeni_sex"] = lbe.fit_transform(df_l["sex"])
df_l.head()

#bu fonk da aynısını yapar 
#AMA yakaladığı değişkeni 0dan dönüştürmeye başlar

total_bill   tip     sex smoker  day    time  size  yeni_sex  daha_yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         1              0
1       10.34  1.66    Male     No  Sun  Dinner     3         0              1
2       21.01  3.50    Male     No  Sun  Dinner     3         0              1
3       23.68  3.31    Male     No  Sun  Dinner     2         0              1
4       24.59  3.61  Female     No  Sun  Dinner     4         1              0

"1 ve Diğerleri (0)" Dönüşümü

In [17]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [16]:
df_l.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex  daha_yeni_sex
0       16.99  1.01  Female     No  Sun  Dinner     2         1              0
1       10.34  1.66    Male     No  Sun  Dinner     3         0              1
2       21.01  3.50    Male     No  Sun  Dinner     3         0              1
3       23.68  3.31    Male     No  Sun  Dinner     2         0              1
4       24.59  3.61  Female     No  Sun  Dinner     4         1              0

In [18]:
df_l["yeni_gun"] = np.where(df_l["day"].str.contains("Sun"),1,0)
#sondaki 1,0 anlamı;
#"Sun" a 1, diğerlerine 0 ver demek

In [21]:
df_l.head(20)

total_bill   tip     sex smoker  day    time  size  yeni_sex  \
0        16.99  1.01  Female     No  Sun  Dinner     2         1   
1        10.34  1.66    Male     No  Sun  Dinner     3         0   
2        21.01  3.50    Male     No  Sun  Dinner     3         0   
3        23.68  3.31    Male     No  Sun  Dinner     2         0   
4        24.59  3.61  Female     No  Sun  Dinner     4         1   
5        25.29  4.71    Male     No  Sun  Dinner     4         0   
6         8.77  2.00    Male     No  Sun  Dinner     2         0   
7        26.88  3.12    Male     No  Sun  Dinner     4         0   
8        15.04  1.96    Male     No  Sun  Dinner     2         0   
9        14.78  3.23    Male     No  Sun  Dinner     2         0   
10       10.27  1.71    Male     No  Sun  Dinner     2         0   
11       35.26  5.00  Female     No  Sun  Dinner     4         1   
12       15.42  1.57    Male     No  Sun  Dinner     2         0   
13       18.43  3.00    Male     No  Sun  Dinner     4         0   
14       14.83  3.02  Female     No  Sun  Dinner     2         1   
15       21.58  3.92    Male     No  Sun  Dinner     2         0   
16       10.33  1.67  Female     No  Sun  Dinner     3         1   
17       16.29  3.71    Male     No  Sun  Dinner     3         0   
18       16.97  3.50  Female     No  Sun  Dinner     3         1   
19       20.65  3.35    Male     No  Sat  Dinner     3         0   

    daha_yeni_sex  yeni_gun  
0               0         1  
1               1         1  
2               1         1  
3               1         1  
4               0         1  
5               1         1  
6               1         1  
7               1         1  
8               1         1  
9               1         1  
10              1         1  
11              0         1  
12              1         1  
13              1         1  
14              0         1  
15              1         1  
16              0         1  
17              1         1  
18              0         1  
19              1         0

ÇOK SINIFLI DÖNÜŞÜM

In [22]:
lbe = preprocessing.LabelEncoder()

In [23]:
df_l["daha_yeni_gun"] = lbe.fit_transform(df_l["day"])
#var olan sınıf sayısı kadar,  1 2 3 4 değişkenleriyle yazdık

In [27]:
df_l.head()

total_bill   tip     sex smoker  day    time  size  yeni_sex  \
0       16.99  1.01  Female     No  Sun  Dinner     2         1   
1       10.34  1.66    Male     No  Sun  Dinner     3         0   
2       21.01  3.50    Male     No  Sun  Dinner     3         0   
3       23.68  3.31    Male     No  Sun  Dinner     2         0   
4       24.59  3.61  Female     No  Sun  Dinner     4         1   

   daha_yeni_sex  yeni_gun  daha_yeni_gun  
0              0         1              2  
1              1         1              2  
2              1         1              2  
3              1         1              2  
4              0         1              2

In [ ]:
# 1 2 3 4 yapınca, günler birbirine üstünlük tasladı, algoritma 
#bir nevi yanlış anladı ve çalıştı.
#bu yüzden one hot dönüşümü yapıcaz.

In [ ]:
#dummy değişken tuzağından kurtulmak için: 
#(kategorik değişkenin sınıf sayısı -1) adet dummy dğşkn olştrlmalı

One-Hot Dönüşümü ve Dummy Değişken Tuzağı

In [28]:
df_one_hot = df.copy()

In [29]:
pd.get_dummies(df_one_hot, columns = ["sex"], prefix= ["sex"]). head()

total_bill   tip smoker  day    time  size  sex_Male  sex_Female
0       16.99  1.01     No  Sun  Dinner     2     False        True
1       10.34  1.66     No  Sun  Dinner     3      True       False
2       21.01  3.50     No  Sun  Dinner     3      True       False
3       23.68  3.31     No  Sun  Dinner     2      True       False
4       24.59  3.61     No  Sun  Dinner     4     False        True

In [30]:
pd.get_dummies(df_one_hot, columns = ["day"], prefix= ["day"]). head()

total_bill   tip     sex smoker    time  size  day_Thur  day_Fri  day_Sat  \
0       16.99  1.01  Female     No  Dinner     2     False    False    False   
1       10.34  1.66    Male     No  Dinner     3     False    False    False   
2       21.01  3.50    Male     No  Dinner     3     False    False    False   
3       23.68  3.31    Male     No  Dinner     2     False    False    False   
4       24.59  3.61  Female     No  Dinner     4     False    False    False   

   day_Sun  
0     True  
1     True  
2     True  
3     True  
4     True

Sürekli Değişkeni Kategorik Değişkene Çevirme

In [ ]:
#ihtiyaç haricinde, gerekmedikçe yapmayı önermiyor hoca

In [31]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [32]:
dff = df.select_dtypes(include = ["float64", "int64"])
#veri setini fonksiyona göndermeden önce seçme işlemi yapmalıymışız
#yoksa hata veriyor aşağıdaki fonk.

In [33]:
est = preprocessing.KBinsDiscretizer(n_bins = [3,2,2], encode = "ordinal", strategy = "quantile").fit(dff)

In [34]:
est.transform(dff)[0:10]

array([[1., 0., 1.],
       [0., 0., 1.],
       [1., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [2., 1., 1.],
       [0., 0., 1.],
       [2., 1., 1.],
       [1., 0., 1.],
       [0., 1., 1.]])

In [ ]:
Değişkeni Indexe, Indexi Değişkene Çevirme

In [35]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [36]:
df["yeni_degisken"] = df.index

In [38]:
df["yeni_degisken"]  = df["yeni_degisken"]  + 10

In [39]:
df.head()

total_bill   tip     sex smoker  day    time  size  yeni_degisken
0       16.99  1.01  Female     No  Sun  Dinner     2             10
1       10.34  1.66    Male     No  Sun  Dinner     3             11
2       21.01  3.50    Male     No  Sun  Dinner     3             12
3       23.68  3.31    Male     No  Sun  Dinner     2             13
4       24.59  3.61  Female     No  Sun  Dinner     4             14

In [40]:
df.index = df["yeni_degisken"]

In [41]:
df.index

Index([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,
       ...
       244, 245, 246, 247, 248, 249, 250, 251, 252, 253],
      dtype='int64', name='yeni_degisken', length=244)